"""
JANSA VISASIST — Module 7 Configuration
Constants for Batch Workflow Engine.
"""

SESSION_SCHEMA_VERSION = "2.2.2"
SESSION_STORAGE_DIR = "sessions"
MAX_CONCURRENT_SESSIONS = 1
CATEGORY_SORT_ORDER = [
    "EASY_WIN_APPROVE",
    "FAST_REJECT",
    "BLOCKED",
    "CONFLICT",
    "WAITING",
    "NOT_STARTED",
]
VALID_DECISIONS = ["VISA_ISSUED", "DEFERRED", "SKIPPED"]
VALID_VISA_VALUES = ["VSO", "VAO", "REF"]
VALID_DECISION_SOURCES = ["manual", "assisted"]
VALID_SESSION_STATUSES = ["CREATED", "IN_PROGRESS", "COMPLETED", "INVALIDATED"]
TERMINAL_STATUSES = ["COMPLETED", "INVALIDATED"]
LARGE_BATCH_THRESHOLD = 500
