"""
Integration tests: End-to-end pipeline with known GrandFichier.

Three layers:
  1. Smoke tests (pipeline runs, outputs exist, traceability, GP2)
  2. Golden semantic regression (row count, schema, per-sheet counts,
     quality distribution, sample rows, row fingerprints)
  3. Golden validation + log regression

Golden files are generated by:
    python -m jansa_visasist.tests.generate_golden
"""

import hashlib
import json
import logging
import os
import tempfile
import warnings
from collections import Counter

import pytest

from jansa_visasist.context import PipelineContext
from jansa_visasist.main import run_pipeline


# ── Path resolution ──────────────────────────────────────────────

_PROJECT_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
_DEFAULT_PATH = os.path.join(_PROJECT_ROOT, "source", "GrandFichier.xlsx")
REFERENCE_FILE = os.environ.get("JANSA_TEST_GRANDFICHIER", _DEFAULT_PATH)

GOLDEN_DIR = os.path.join(os.path.dirname(__file__), "golden")
GOLDEN_SNAPSHOT = os.path.join(GOLDEN_DIR, "golden_snapshot.json")
GOLDEN_VALIDATION = os.path.join(GOLDEN_DIR, "golden_validation.json")
GOLDEN_LOG_SUMMARY = os.path.join(GOLDEN_DIR, "golden_log_summary.json")


# ── Helpers ──────────────────────────────────────────────────────

def _row_fingerprint(row: dict) -> str:
    """Must match generate_golden._row_fingerprint exactly."""
    parts = [
        str(row.get("row_id", "")),
        str(row.get("source_sheet", "")),
        str(row.get("source_row", "")),
        str(row.get("document", "")),
        str(row.get("document_raw", "")),
        str(row.get("ind", "")),
        str(row.get("visa_global", "")),
        str(row.get("row_quality", "")),
        str(row.get("date_diffusion", "")),
        str(row.get("date_reception", "")),
        str(row.get("titre", ""))[:80],
    ]
    raw = "|".join(parts)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()[:16]


def _load_golden(path):
    """Load a golden JSON file, return None if missing."""
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


# ── Shared fixture: single pipeline run for all tests ────────────

@pytest.fixture(scope="module")
def pipeline_result():
    """
    Run the pipeline once and return (master_data, ctx, tmpdir_path).
    Shared across all tests in this module to avoid re-running the
    ~12s pipeline for each test.
    """
    if not os.path.exists(REFERENCE_FILE):
        pytest.skip(f"Reference GrandFichier not found at {REFERENCE_FILE}")

    tmpdir = tempfile.mkdtemp(prefix="jansa_golden_")
    ctx = PipelineContext(input_path=REFERENCE_FILE, output_dir=tmpdir)

    # Suppress openpyxl's noisy UserWarnings about data validation / styles
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
        exit_code = run_pipeline(ctx)

    assert exit_code == 0, f"Pipeline failed with exit code {exit_code}"

    with open(os.path.join(tmpdir, "master_dataset.json"), encoding="utf-8") as f:
        master = json.load(f)

    return master, ctx, tmpdir


# ═════════════════════════════════════════════════════════════════
# Layer 1 — Smoke tests
# ═════════════════════════════════════════════════════════════════

class TestSmoke:
    """Basic pipeline health checks."""

    def test_pipeline_completes(self, pipeline_result):
        master, ctx, _ = pipeline_result
        assert ctx.total_rows > 0

    def test_all_outputs_created(self, pipeline_result):
        _, _, tmpdir = pipeline_result
        expected = [
            "master_dataset.json",
            "master_dataset.csv",
            "import_log.json",
            "import_log.csv",
            "header_mapping_report.json",
            "validation_report.json",
        ]
        for fname in expected:
            assert os.path.exists(os.path.join(tmpdir, fname)), f"Missing: {fname}"

    def test_no_silent_row_drops(self, pipeline_result):
        master, ctx, _ = pipeline_result
        assert len(master) == ctx.total_rows
        assert sum(ctx.sheet_row_counts.values()) == ctx.total_rows

    def test_every_row_has_traceability(self, pipeline_result):
        master, _, _ = pipeline_result
        for row in master:
            assert row["source_sheet"] is not None, f"row {row.get('row_id')}"
            assert row["source_row"] is not None, f"row {row.get('row_id')}"
            assert row["row_id"] is not None
            assert row["row_quality"] in ("OK", "WARNING", "ERROR")

    def test_gp2_no_empty_strings(self, pipeline_result):
        master, _, _ = pipeline_result
        normalized_fields = [
            "document", "visa_global", "ind",
            "date_diffusion", "date_reception", "date_contractuelle_visa",
        ]
        for row in master:
            for field in normalized_fields:
                val = row.get(field)
                if val is not None:
                    assert val != "", \
                        f"GP2 violation: empty string in {field}, row {row.get('row_id')}"


# ═════════════════════════════════════════════════════════════════
# Layer 2 — Golden semantic regression
# ═════════════════════════════════════════════════════════════════

class TestGoldenSnapshot:
    """Compare pipeline output against the golden semantic snapshot."""

    @pytest.fixture(autouse=True)
    def _load_snapshot(self):
        self.snapshot = _load_golden(GOLDEN_SNAPSHOT)
        if self.snapshot is None:
            pytest.skip(
                "Golden snapshot not found. Generate with: "
                "python -m jansa_visasist.tests.generate_golden"
            )

    def test_row_count(self, pipeline_result):
        master, _, _ = pipeline_result
        expected = self.snapshot["total_rows"]
        assert len(master) == expected, \
            f"Row count changed: expected {expected}, got {len(master)}"

    def test_schema_columns(self, pipeline_result):
        master, _, _ = pipeline_result
        actual_schema = sorted(master[0].keys()) if master else []
        expected_schema = self.snapshot["schema"]
        assert actual_schema == expected_schema, \
            f"Schema mismatch.\nAdded: {set(actual_schema) - set(expected_schema)}\n" \
            f"Removed: {set(expected_schema) - set(actual_schema)}"

    def test_per_sheet_row_counts(self, pipeline_result):
        master, _, _ = pipeline_result
        actual_counts = dict(Counter(row["source_sheet"] for row in master))
        expected_counts = self.snapshot["sheet_counts"]
        assert actual_counts == expected_counts, \
            f"Per-sheet row counts changed:\n" \
            f"Expected: {expected_counts}\nActual:   {actual_counts}"

    def test_quality_distribution(self, pipeline_result):
        master, _, _ = pipeline_result
        actual_dist = dict(Counter(row["row_quality"] for row in master))
        expected_dist = self.snapshot["quality_distribution"]
        assert actual_dist == expected_dist, \
            f"Quality distribution changed:\n" \
            f"Expected: {expected_dist}\nActual:   {actual_dist}"

    def test_visa_distribution(self, pipeline_result):
        master, _, _ = pipeline_result
        actual_dist = dict(Counter(str(row.get("visa_global")) for row in master))
        expected_dist = self.snapshot["visa_distribution"]
        assert actual_dist == expected_dist, \
            f"Visa distribution changed:\n" \
            f"Expected: {expected_dist}\nActual:   {actual_dist}"

    def test_header_mapping_summary(self, pipeline_result):
        _, _, tmpdir = pipeline_result
        with open(os.path.join(tmpdir, "header_mapping_report.json"), encoding="utf-8") as f:
            actual_report = json.load(f)

        expected_summary = self.snapshot["header_mapping_summary"]

        # Compare sheet-by-sheet
        actual_summary = []
        for r in actual_report:
            actual_summary.append({
                "sheet": r["sheet"],
                "header_row_detected": r["header_row_detected"],
                "core_columns_mapped": r["core_columns_mapped"],
                "mapping_confidence": r["mapping_confidence"],
                "approvers_detected": r["approvers_detected"],
            })

        assert len(actual_summary) == len(expected_summary), \
            f"Sheet count: {len(actual_summary)} vs {len(expected_summary)}"

        for act, exp in zip(actual_summary, expected_summary):
            assert act == exp, \
                f"Header mapping changed for sheet '{exp['sheet']}':\n" \
                f"Expected: {exp}\nActual:   {act}"

    def test_sample_rows(self, pipeline_result):
        """Spot-check representative rows at known positions."""
        master, _, _ = pipeline_result
        for sample in self.snapshot["sample_rows"]:
            idx = sample["index"]
            assert idx < len(master), f"Sample index {idx} out of range"
            actual_row = master[idx]

            for key in ("row_id", "source_sheet", "source_row", "document",
                        "ind", "visa_global", "row_quality"):
                assert actual_row.get(key) == sample.get(key), \
                    f"Sample row {idx}, field '{key}': " \
                    f"{actual_row.get(key)!r} != {sample.get(key)!r}"

    def test_row_fingerprints(self, pipeline_result):
        """Every row's identity+key-field fingerprint matches golden."""
        master, _, _ = pipeline_result
        expected_fps = self.snapshot["row_fingerprints"]

        assert len(master) == len(expected_fps), "Row count mismatch"

        mismatches = []
        for i, (row, exp) in enumerate(zip(master, expected_fps)):
            actual_fp = _row_fingerprint(row)
            if actual_fp != exp["fp"]:
                mismatches.append(
                    f"  Row {i} (row_id={exp['row_id']}): "
                    f"expected {exp['fp']}, got {actual_fp}"
                )

        assert len(mismatches) == 0, \
            f"{len(mismatches)} row fingerprint(s) changed:\n" + \
            "\n".join(mismatches[:20]) + \
            (f"\n  ... and {len(mismatches) - 20} more" if len(mismatches) > 20 else "")


# ═════════════════════════════════════════════════════════════════
# Layer 3 — Golden validation report + log summary
# ═════════════════════════════════════════════════════════════════

class TestGoldenValidation:
    """Compare validation report against golden reference."""

    @pytest.fixture(autouse=True)
    def _load_golden_validation(self, pipeline_result):
        self.golden = _load_golden(GOLDEN_VALIDATION)
        if self.golden is None:
            pytest.skip("Golden validation not found. Run generate_golden.")
        _, _, self.tmpdir = pipeline_result

    def test_validation_checks_match(self):
        with open(os.path.join(self.tmpdir, "validation_report.json"), encoding="utf-8") as f:
            actual = json.load(f)

        for check_name, expected_result in self.golden.items():
            assert check_name in actual, f"Missing validation check: {check_name}"
            assert actual[check_name]["passed"] == expected_result["passed"], \
                f"Validation '{check_name}' changed: " \
                f"expected passed={expected_result['passed']}, " \
                f"got passed={actual[check_name]['passed']}"


class TestGoldenLogSummary:
    """Compare import log severity/category counts against golden reference."""

    @pytest.fixture(autouse=True)
    def _load_golden_log(self, pipeline_result):
        self.golden = _load_golden(GOLDEN_LOG_SUMMARY)
        if self.golden is None:
            pytest.skip("Golden log summary not found. Run generate_golden.")
        _, _, self.tmpdir = pipeline_result

    def test_log_severity_counts(self):
        with open(os.path.join(self.tmpdir, "import_log.json"), encoding="utf-8") as f:
            actual_log = json.load(f)

        actual_sev = dict(Counter(e["severity"] for e in actual_log))
        expected_sev = self.golden["severity_counts"]
        assert actual_sev == expected_sev, \
            f"Log severity counts changed:\n" \
            f"Expected: {expected_sev}\nActual:   {actual_sev}"

    def test_log_category_counts(self):
        with open(os.path.join(self.tmpdir, "import_log.json"), encoding="utf-8") as f:
            actual_log = json.load(f)

        actual_cat = dict(Counter(e["category"] for e in actual_log))
        expected_cat = self.golden["category_counts"]
        assert actual_cat == expected_cat, \
            f"Log category counts changed:\n" \
            f"Expected: {expected_cat}\nActual:   {actual_cat}"
